--[[You can modify priority if you feel like it,1 in array 
is the biggest and 7 is the lowest
https://create.roblox.com/docs/reference/engine/enums/AnimationPriority
]]
return {
	[1] = Enum.AnimationPriority.Action4;
	[2] = Enum.AnimationPriority.Action3;
	[3] = Enum.AnimationPriority.Action2;
	[4] = Enum.AnimationPriority.Action;
	[5] = Enum.AnimationPriority.Movement;
	[6] = Enum.AnimationPriority.Idle;
	[7] = Enum.AnimationPriority.Core
}
